# 暂时没有用到，直接到database_init中去更改信息
database:
  driver: mysql
  host: 111.92.243.152
  port: 3306
  Dbname: datatest
  username: datatest
  password: EYxwxRsNfYTn7SN7
  charset: utf8mb4
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log
